name: .NET Release

on:
  push:
    tags:
      - '*'  # Trigger only on tag pushes like v1.0.0, v2.3, etc.

permissions:
  contents: write  # Required to create releases and upload assets

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Publish VRCVideoCacher as self-contained EXE
        run: >
          dotnet publish VRCVideoCacher/VRCVideoCacher.csproj
          --configuration Release
          --runtime win-x64
          --self-contained true
          -p:PublishSingleFile=true
          -p:IncludeNativeLibrariesForSelfExtract=true
          -p:PublishTrimmed=false
          -o publish_output

      - name: Create GitHub Release and Upload EXE
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: publish_output/VRCVideoCacher.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
